marshalutils.cpp: Add missing declarations for operator overloads
This fixes clang-11 errors e.g.

| ../../recipe-sysroot/usr/include/QtDBus/qdbusargument.h:276:13: error: invalid operands to binary expression ('const QDBusArgument' and 'RouteStructure')
|         arg >> item;
|         ~~~ ^  ~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>